# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import qdarkstyle

'''
        Приложение калькулятор
+ Есть ф-ция удаление введеной строки
+ обработка ошибки деления на ноль
+ обработка нажатия несколько раз на знак операции
- только целочисленные цифры - не реализована работа с дробными цифрами и работа кнопки ','.
- требует доработки функционала, но работает основное
'''


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 426)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, -1, 301, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_result.setFont(font)
        # self.label_result.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_result.setObjectName("label_result")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(0, 320, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        # self.btn_0.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_0.setObjectName("btn_0")
        self.btn_res = QtWidgets.QPushButton(self.centralwidget)
        self.btn_res.setGeometry(QtCore.QRect(200, 320, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_res.setFont(font)
        # self.btn_res.setStyleSheet("background-color: rgb(244, 179, 255);\n"
# "background-color: rgb(252, 196, 255);")
        self.btn_res.setObjectName("btn_res")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        # self.btn_7.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_7.setObjectName("btn_7")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        # self.btn_4.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        # self.btn_5.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_5.setObjectName("btn_5")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        # self.btn_2.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        # self.btn_3.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_3.setObjectName("btn_3")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        # self.btn_1.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_1.setObjectName("btn_1")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        # self.btn_8.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_8.setObjectName("btn_8")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        # self.btn_6.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_6.setObjectName("btn_6")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        # self.btn_9.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_9.setObjectName("btn_9")
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setGeometry(QtCore.QRect(300, 80, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_divide.setFont(font)
        # self.btn_divide.setStyleSheet("background-color: rgb(255, 204, 83);")
        self.btn_divide.setObjectName("btn_divide")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(300, 160, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mult.setFont(font)
        # self.btn_mult.setStyleSheet("background-color: rgb(255, 204, 83);")
        self.btn_mult.setObjectName("btn_mult")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(300, 240, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        # self.btn_minus.setStyleSheet("background-color: rgb(255, 204, 83);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(300, 320, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        # self.btn_plus.setStyleSheet("background-color: rgb(255, 204, 83);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(300, 0, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        # self.btn_clear.setStyleSheet("background-color: rgb(244, 179, 255);\n"
# "background-color: rgb(252, 196, 255);")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_comma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comma.setGeometry(QtCore.QRect(100, 320, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btn_comma.setFont(font)
        # self.btn_comma.setStyleSheet("background-color: rgb(255, 255, 101);")
        self.btn_comma.setObjectName("btn_comma")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 998, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

        self.add_functions()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_res.setText(_translate("MainWindow", "="))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_divide.setText(_translate("MainWindow", "/"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_comma.setText(_translate("MainWindow", ","))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Вид"))
        self.action.setText(_translate("MainWindow", "Сохранить"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))

    def add_functions(self):
        self.is_res = False
        
        self.btn_0.clicked.connect(lambda: self.write_number(self.btn_0.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.btn_divide.clicked.connect(lambda: self.write_sign(self.btn_divide.text()))
        self.btn_mult.clicked.connect(lambda: self.write_sign(self.btn_mult.text()))
        self.btn_minus.clicked.connect(lambda: self.write_sign(self.btn_minus.text()))
        self.btn_plus.clicked.connect(lambda: self.write_sign(self.btn_plus.text()))
        self.btn_clear.clicked.connect(self.clear_to0)
        
        self.btn_res.clicked.connect(self.results)

    def clear_to0(self):
        self.label_result.setText("0")

    def write_number_original_my(self, number):
        last_inp = self.label_result.text()[len(self.label_result.text())-1]
        if (self.label_result.text() == "0" or self.is_res):
            if number in ['/', '*', '+']:
                pass
        elif self.label_result.text() == "0" or self.is_res:
            self.label_result.setText(number)
            self.is_res = False
        elif last_inp in ['/', '*', '-', '+']:
            if number.isdigit():
                self.label_result.setText(self.label_result.text() + number)

        elif number.isdigit(): 
        # elif number.isdigit() or number in ['/', '*', '-', '+']: 
            self.label_result.setText(self.label_result.text() + number)
        elif self.label_result.text() in ['/', '*', '+']:
            self.label_result.setText(self.label_result.text()[0:len(self.label_result.text())-1] + number)

            # print('else', self.label_result.text()[len(self.label_result.text())-1])
            pass

    def write_number(self, number):
        if self.label_result.text() == "0" or self.is_res:
            self.label_result.setText(number)
            self.is_res = False
        else:
            self.label_result.setText(self.label_result.text() + number)



    def write_sign(self, sign):
        last_inp = self.label_result.text()[len(self.label_result.text())-1]

        if last_inp == sign:
            pass
        elif last_inp in ['/', '*', '+', '-']:
            print("input is sign")
            self.label_result.setText(self.label_result.text()[0:len(self.label_result.text())-1] + sign)
        else:
            self.label_result.setText(self.label_result.text() + sign)


    def results(self):
        last_inp = self.label_result.text()[len(self.label_result.text())-1]
        if not self.is_res and last_inp not in ['/', '*', '-', '+']:
            try:
                res = round(eval(self.label_result.text()), 5)
                self.label_result.setText(str(res))
                self.is_res = True
            except ZeroDivisionError:
                self.label_result.setText("0")
                error = QMessageBox()
                error.setWindowTitle("Ошибка")
                error.setText("Деление на ноль невозможно")
                error.setIcon(QMessageBox.Warning)
                error.setStandardButtons(QMessageBox.Ok)  # QMessageBox.Close
                error.setDetailedText("Нельзя делить на ноль.\nВведите верное выражение для вычисления. ")

                error.buttonClicked.connect(self.popup_action)

                error.exec_()

        else:  # выведем выспылвающее окно
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Сечас это действие выполнить нельзя")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Reset|QMessageBox.Ok)  # QMessageBox.Close
            # error.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)  # QMessageBox.Close
            # error.setDefaultButton(QMessageBox.Cancel)  # подсветка указанной кнопки в вспылвающем окне
            error.setInformativeText("Два раза действие не выполнить")
            error.setDetailedText("Введите верное выражение для вычисления ")

            error.buttonClicked.connect(self.popup_action)

            error.exec_()


    def popup_action(self, btn_name):
        if btn_name.text() == "Ok":
            print("ok")
        elif btn_name.text() == "Reset":
            self.label_result.setText("0")
            self.is_res = False


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())  # set dark style sheet
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
